### ISSUE TITLE
管理员账户及密码是多少？

### ISSUE THREAD

**Issue by feiruyun** [cube-ai/cubeai#3]
管理员账户及密码是多少？在源码里找了没找到。
谢谢！

**Comment by zjfpeter0** [comment]
试试admin admin ------------------ 原始邮件 ------------------
发件人: "feiruyun"<notifications@github.com>
发送时间: 2019年10月29日(星期二) 下午5:55
收件人: "cube-ai/cubeai"<cubeai@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [cube-ai/cubeai] 管理员账户及密码是多少？ (#3)



管理员账户及密码是多少？在源码里找了没找到。
 谢谢！
 
&mdash;

**Comment by feiruyun** [comment]
管理员用户名和密码：
admin
admin
好使，谢谢。（之前也试过admin不好使，以为是别的呢）
