### ISSUE TITLE
sh: build-docker.sh: No such file or directory

### ISSUE THREAD

**Issue by zhangchunsheng** [cube-ai/cubeai#42]
sh build-all-python.sh
build-all-python.sh: line 1: cd: /home//cubeai/uaa-python: No such file or directory
sh: build-docker.sh: No such file or directory
build-all-python.sh: line 4: cd: /home//cubeai/gateway-python: No such file or directory
sh: build-docker.sh: No such file or directory
build-all-python.sh: line 7: cd: /home//cubeai/portal-python: No such file or directory
build-all-python.sh: line 8: yarn: command not found
sh: build-docker.sh: No such file or directory
build-all-python.sh: line 11: cd: /home//cubeai/ppersonal-python: No such file or directory
build-all-python.sh: line 12: yarn: command not found
sh: build-docker.sh: No such file or directory
build-all-python.sh: line 15: cd: /home//cubeai/pmodelhub-python: No such file or directory
build-all-python.sh: line 16: yarn: command not found
sh: build-docker.sh: No such file or directory
build-all-python.sh: line 19: cd: /home//cubeai/popen-python: No such file or directory
build-all-python.sh: line 20: yarn: command not found
sh: build-docker.sh: No such file or directory
build-all-python.sh: line 23: cd: /home//cubeai/umm-python: No such file or directory
sh: build-docker.sh: No such file or directory
build-all-python.sh: line 26: cd: /home//cubeai/umu-python: No such file or directory
sh: build-docker.sh: No such file or directory
build-all-python.sh: line 29: cd: /home//cubeai/umd-python: No such file or directory
sh: build-docker.sh: No such file or directory
build-all-python.sh: line 32: cd: /home//cubeai/ability-python: No such file or directory
sh: build-docker.sh: No such file or directory
build-all-python.sh: line 35: cd: /home//cubeai/pface-python: No such file or directory
build-all-python.sh: line 36: yarn: command not found
sh: build-docker.sh: No such file or directory
build-all-python.sh: line 39: cd: /home//cubeai/uface-python: No such file or directory
sh: build-docker.sh: No such file or directory

**Comment by smile-luobin** [comment]
It is a bug, use relative paths replaces the absolute paths, such as: "cd ../uaa-python" -> "cd ~/cubeai/uaa-python".

**Comment by zhangchunsheng** [comment]
> It is a bug, use relative paths replaces the absolute paths, such as: "cd ../uaa-python" -> "cd ~/cubeai/uaa-python".

ok
